//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model3", "BookPublisher", "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.Dictionary), "Publisher", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication3.Publisher), true)]
[assembly: EdmRelationshipAttribute("Model3", "BookAuthor", "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.Dictionary), "Author", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.Author))]
[assembly: EdmRelationshipAttribute("Model3", "PublisherLocation", "Publisher", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication3.Publisher), "Location", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.Location), true)]
[assembly: EdmRelationshipAttribute("Model3", "DictionaryCategory", "Dictionary", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.Dictionary), "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.Category))]
[assembly: EdmRelationshipAttribute("Model3", "DictionaryMention", "Dictionary", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.Dictionary), "Mention", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.Mention))]
[assembly: EdmRelationshipAttribute("Model3", "DictionaryAcknowledgement", "Dictionary", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.Dictionary), "Acknowledgement", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.Acknowledgement))]
[assembly: EdmRelationshipAttribute("Model3", "LanguageToL", "Language", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication3.Language), "ToL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.ToL), true)]
[assembly: EdmRelationshipAttribute("Model3", "DictionaryToL", "Dictionary", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication3.Dictionary), "ToL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.ToL), true)]
[assembly: EdmRelationshipAttribute("Model3", "LanguageFromL", "Language", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication3.Language), "FromL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.FromL), true)]
[assembly: EdmRelationshipAttribute("Model3", "DictionaryFromL", "Dictionary", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication3.Dictionary), "FromL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.FromL), true)]
[assembly: EdmRelationshipAttribute("Model3", "ScriptFromS", "Script", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication3.Script), "FromS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.FromS), true)]
[assembly: EdmRelationshipAttribute("Model3", "DictionaryFromS", "Dictionary", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication3.Dictionary), "FromS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.FromS), true)]
[assembly: EdmRelationshipAttribute("Model3", "DictionaryToS", "Dictionary", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication3.Dictionary), "ToS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.ToS), true)]
[assembly: EdmRelationshipAttribute("Model3", "ScriptToS", "Script", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication3.Script), "ToS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication3.ToS), true)]

#endregion

namespace WpfApplication3
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model3Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model3Container object using the connection string found in the 'Model3Container' section of the application configuration file.
        /// </summary>
        public Model3Container() : base("name=Model3Container", "Model3Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model3Container object.
        /// </summary>
        public Model3Container(string connectionString) : base(connectionString, "Model3Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model3Container object.
        /// </summary>
        public Model3Container(EntityConnection connection) : base(connection, "Model3Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dictionary> Dictionaries
        {
            get
            {
                if ((_Dictionaries == null))
                {
                    _Dictionaries = base.CreateObjectSet<Dictionary>("Dictionaries");
                }
                return _Dictionaries;
            }
        }
        private ObjectSet<Dictionary> _Dictionaries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Publisher> Publishers
        {
            get
            {
                if ((_Publishers == null))
                {
                    _Publishers = base.CreateObjectSet<Publisher>("Publishers");
                }
                return _Publishers;
            }
        }
        private ObjectSet<Publisher> _Publishers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Author> Authors
        {
            get
            {
                if ((_Authors == null))
                {
                    _Authors = base.CreateObjectSet<Author>("Authors");
                }
                return _Authors;
            }
        }
        private ObjectSet<Author> _Authors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Location> Locations
        {
            get
            {
                if ((_Locations == null))
                {
                    _Locations = base.CreateObjectSet<Location>("Locations");
                }
                return _Locations;
            }
        }
        private ObjectSet<Location> _Locations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Mention> Mentions
        {
            get
            {
                if ((_Mentions == null))
                {
                    _Mentions = base.CreateObjectSet<Mention>("Mentions");
                }
                return _Mentions;
            }
        }
        private ObjectSet<Mention> _Mentions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Acknowledgement> Acknowledgements
        {
            get
            {
                if ((_Acknowledgements == null))
                {
                    _Acknowledgements = base.CreateObjectSet<Acknowledgement>("Acknowledgements");
                }
                return _Acknowledgements;
            }
        }
        private ObjectSet<Acknowledgement> _Acknowledgements;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Language> Languages
        {
            get
            {
                if ((_Languages == null))
                {
                    _Languages = base.CreateObjectSet<Language>("Languages");
                }
                return _Languages;
            }
        }
        private ObjectSet<Language> _Languages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FromL> FromLs
        {
            get
            {
                if ((_FromLs == null))
                {
                    _FromLs = base.CreateObjectSet<FromL>("FromLs");
                }
                return _FromLs;
            }
        }
        private ObjectSet<FromL> _FromLs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ToL> ToLs
        {
            get
            {
                if ((_ToLs == null))
                {
                    _ToLs = base.CreateObjectSet<ToL>("ToLs");
                }
                return _ToLs;
            }
        }
        private ObjectSet<ToL> _ToLs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Script> Scripts
        {
            get
            {
                if ((_Scripts == null))
                {
                    _Scripts = base.CreateObjectSet<Script>("Scripts");
                }
                return _Scripts;
            }
        }
        private ObjectSet<Script> _Scripts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FromS> FromS
        {
            get
            {
                if ((_FromS == null))
                {
                    _FromS = base.CreateObjectSet<FromS>("FromS");
                }
                return _FromS;
            }
        }
        private ObjectSet<FromS> _FromS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ToS> ToS
        {
            get
            {
                if ((_ToS == null))
                {
                    _ToS = base.CreateObjectSet<ToS>("ToS");
                }
                return _ToS;
            }
        }
        private ObjectSet<ToS> _ToS;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dictionaries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDictionaries(Dictionary dictionary)
        {
            base.AddObject("Dictionaries", dictionary);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Publishers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPublishers(Publisher publisher)
        {
            base.AddObject("Publishers", publisher);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Authors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuthors(Author author)
        {
            base.AddObject("Authors", author);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Locations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocations(Location location)
        {
            base.AddObject("Locations", location);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Mentions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMentions(Mention mention)
        {
            base.AddObject("Mentions", mention);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Acknowledgements EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAcknowledgements(Acknowledgement acknowledgement)
        {
            base.AddObject("Acknowledgements", acknowledgement);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Languages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLanguages(Language language)
        {
            base.AddObject("Languages", language);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FromLs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFromLs(FromL fromL)
        {
            base.AddObject("FromLs", fromL);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ToLs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToToLs(ToL toL)
        {
            base.AddObject("ToLs", toL);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Scripts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScripts(Script script)
        {
            base.AddObject("Scripts", script);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FromS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFromS(FromS fromS)
        {
            base.AddObject("FromS", fromS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ToS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToToS(ToS toS)
        {
            base.AddObject("ToS", toS);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="Acknowledgement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Acknowledgement : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Acknowledgement object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static Acknowledgement CreateAcknowledgement(global::System.Int32 id, global::System.String name, global::System.String type)
        {
            Acknowledgement acknowledgement = new Acknowledgement();
            acknowledgement.Id = id;
            acknowledgement.Name = name;
            acknowledgement.Type = type;
            return acknowledgement;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryAcknowledgement", "Dictionary")]
        public EntityCollection<Dictionary> Dictionaries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Dictionary>("Model3.DictionaryAcknowledgement", "Dictionary");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Dictionary>("Model3.DictionaryAcknowledgement", "Dictionary", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="Author")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Author : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Author object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Author CreateAuthor(global::System.Int32 id, global::System.String name)
        {
            Author author = new Author();
            author.Id = id;
            author.Name = name;
            return author;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "BookAuthor", "Book")]
        public EntityCollection<Dictionary> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Dictionary>("Model3.BookAuthor", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Dictionary>("Model3.BookAuthor", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static Category CreateCategory(global::System.Int32 id, global::System.String description)
        {
            Category category = new Category();
            category.Id = id;
            category.Description = description;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryCategory", "Dictionary")]
        public EntityCollection<Dictionary> Dictionaries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Dictionary>("Model3.DictionaryCategory", "Dictionary");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Dictionary>("Model3.DictionaryCategory", "Dictionary", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="Dictionary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dictionary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dictionary object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="iSBN">Initial value of the ISBN property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="edition">Initial value of the Edition property.</param>
        /// <param name="volume">Initial value of the Volume property.</param>
        /// <param name="part">Initial value of the Part property.</param>
        /// <param name="publisherId">Initial value of the PublisherId property.</param>
        /// <param name="copies">Initial value of the Copies property.</param>
        /// <param name="words">Initial value of the Words property.</param>
        public static Dictionary CreateDictionary(global::System.Int32 id, global::System.Int32 iSBN, global::System.String title, global::System.Int32 edition, global::System.Int32 volume, global::System.Int32 part, global::System.Int32 publisherId, global::System.String copies, global::System.String words)
        {
            Dictionary dictionary = new Dictionary();
            dictionary.Id = id;
            dictionary.ISBN = iSBN;
            dictionary.Title = title;
            dictionary.Edition = edition;
            dictionary.Volume = volume;
            dictionary.Part = part;
            dictionary.PublisherId = publisherId;
            dictionary.Copies = copies;
            dictionary.Words = words;
            return dictionary;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                OnISBNChanging(value);
                ReportPropertyChanging("ISBN");
                _ISBN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISBN");
                OnISBNChanged();
            }
        }
        private global::System.Int32 _ISBN;
        partial void OnISBNChanging(global::System.Int32 value);
        partial void OnISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Edition
        {
            get
            {
                return _Edition;
            }
            set
            {
                OnEditionChanging(value);
                ReportPropertyChanging("Edition");
                _Edition = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Edition");
                OnEditionChanged();
            }
        }
        private global::System.Int32 _Edition;
        partial void OnEditionChanging(global::System.Int32 value);
        partial void OnEditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                OnVolumeChanging(value);
                ReportPropertyChanging("Volume");
                _Volume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Volume");
                OnVolumeChanged();
            }
        }
        private global::System.Int32 _Volume;
        partial void OnVolumeChanging(global::System.Int32 value);
        partial void OnVolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Part
        {
            get
            {
                return _Part;
            }
            set
            {
                OnPartChanging(value);
                ReportPropertyChanging("Part");
                _Part = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Part");
                OnPartChanged();
            }
        }
        private global::System.Int32 _Part;
        partial void OnPartChanging(global::System.Int32 value);
        partial void OnPartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PublisherId
        {
            get
            {
                return _PublisherId;
            }
            set
            {
                OnPublisherIdChanging(value);
                ReportPropertyChanging("PublisherId");
                _PublisherId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublisherId");
                OnPublisherIdChanged();
            }
        }
        private global::System.Int32 _PublisherId;
        partial void OnPublisherIdChanging(global::System.Int32 value);
        partial void OnPublisherIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Copies
        {
            get
            {
                return _Copies;
            }
            set
            {
                OnCopiesChanging(value);
                ReportPropertyChanging("Copies");
                _Copies = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Copies");
                OnCopiesChanged();
            }
        }
        private global::System.String _Copies;
        partial void OnCopiesChanging(global::System.String value);
        partial void OnCopiesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Words
        {
            get
            {
                return _Words;
            }
            set
            {
                OnWordsChanging(value);
                ReportPropertyChanging("Words");
                _Words = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Words");
                OnWordsChanged();
            }
        }
        private global::System.String _Words;
        partial void OnWordsChanging(global::System.String value);
        partial void OnWordsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "BookPublisher", "Publisher")]
        public Publisher Publisher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("Model3.BookPublisher", "Publisher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("Model3.BookPublisher", "Publisher").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Publisher> PublisherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("Model3.BookPublisher", "Publisher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Publisher>("Model3.BookPublisher", "Publisher", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "BookAuthor", "Author")]
        public EntityCollection<Author> Authors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Author>("Model3.BookAuthor", "Author");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Author>("Model3.BookAuthor", "Author", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryCategory", "Category")]
        public EntityCollection<Category> Categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Category>("Model3.DictionaryCategory", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Category>("Model3.DictionaryCategory", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryMention", "Mention")]
        public EntityCollection<Mention> Mentions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Mention>("Model3.DictionaryMention", "Mention");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Mention>("Model3.DictionaryMention", "Mention", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryAcknowledgement", "Acknowledgement")]
        public EntityCollection<Acknowledgement> Acknowledgements
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Acknowledgement>("Model3.DictionaryAcknowledgement", "Acknowledgement");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Acknowledgement>("Model3.DictionaryAcknowledgement", "Acknowledgement", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryToL", "ToL")]
        public EntityCollection<ToL> ToLs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ToL>("Model3.DictionaryToL", "ToL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ToL>("Model3.DictionaryToL", "ToL", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryFromL", "FromL")]
        public EntityCollection<FromL> FromLs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FromL>("Model3.DictionaryFromL", "FromL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FromL>("Model3.DictionaryFromL", "FromL", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryFromS", "FromS")]
        public EntityCollection<FromS> FromS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FromS>("Model3.DictionaryFromS", "FromS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FromS>("Model3.DictionaryFromS", "FromS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryToS", "ToS")]
        public EntityCollection<ToS> ToS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ToS>("Model3.DictionaryToS", "ToS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ToS>("Model3.DictionaryToS", "ToS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="FromL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FromL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FromL object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="languageId">Initial value of the LanguageId property.</param>
        /// <param name="dictionaryId">Initial value of the DictionaryId property.</param>
        public static FromL CreateFromL(global::System.Int32 id, global::System.Int32 languageId, global::System.Int32 dictionaryId)
        {
            FromL fromL = new FromL();
            fromL.Id = id;
            fromL.LanguageId = languageId;
            fromL.DictionaryId = dictionaryId;
            return fromL;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                OnLanguageIdChanging(value);
                ReportPropertyChanging("LanguageId");
                _LanguageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LanguageId");
                OnLanguageIdChanged();
            }
        }
        private global::System.Int32 _LanguageId;
        partial void OnLanguageIdChanging(global::System.Int32 value);
        partial void OnLanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DictionaryId
        {
            get
            {
                return _DictionaryId;
            }
            set
            {
                OnDictionaryIdChanging(value);
                ReportPropertyChanging("DictionaryId");
                _DictionaryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DictionaryId");
                OnDictionaryIdChanged();
            }
        }
        private global::System.Int32 _DictionaryId;
        partial void OnDictionaryIdChanging(global::System.Int32 value);
        partial void OnDictionaryIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "LanguageFromL", "Language")]
        public Language Language
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("Model3.LanguageFromL", "Language").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("Model3.LanguageFromL", "Language").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Language> LanguageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("Model3.LanguageFromL", "Language");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Language>("Model3.LanguageFromL", "Language", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryFromL", "Dictionary")]
        public Dictionary Dictionary
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryFromL", "Dictionary").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryFromL", "Dictionary").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dictionary> DictionaryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryFromL", "Dictionary");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dictionary>("Model3.DictionaryFromL", "Dictionary", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="FromS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FromS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FromS object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="scriptId">Initial value of the ScriptId property.</param>
        /// <param name="dictionaryId">Initial value of the DictionaryId property.</param>
        public static FromS CreateFromS(global::System.Int32 id, global::System.Int32 scriptId, global::System.Int32 dictionaryId)
        {
            FromS fromS = new FromS();
            fromS.Id = id;
            fromS.ScriptId = scriptId;
            fromS.DictionaryId = dictionaryId;
            return fromS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScriptId
        {
            get
            {
                return _ScriptId;
            }
            set
            {
                OnScriptIdChanging(value);
                ReportPropertyChanging("ScriptId");
                _ScriptId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScriptId");
                OnScriptIdChanged();
            }
        }
        private global::System.Int32 _ScriptId;
        partial void OnScriptIdChanging(global::System.Int32 value);
        partial void OnScriptIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DictionaryId
        {
            get
            {
                return _DictionaryId;
            }
            set
            {
                OnDictionaryIdChanging(value);
                ReportPropertyChanging("DictionaryId");
                _DictionaryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DictionaryId");
                OnDictionaryIdChanged();
            }
        }
        private global::System.Int32 _DictionaryId;
        partial void OnDictionaryIdChanging(global::System.Int32 value);
        partial void OnDictionaryIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "ScriptFromS", "Script")]
        public Script Script
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Script>("Model3.ScriptFromS", "Script").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Script>("Model3.ScriptFromS", "Script").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Script> ScriptReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Script>("Model3.ScriptFromS", "Script");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Script>("Model3.ScriptFromS", "Script", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryFromS", "Dictionary")]
        public Dictionary Dictionary
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryFromS", "Dictionary").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryFromS", "Dictionary").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dictionary> DictionaryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryFromS", "Dictionary");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dictionary>("Model3.DictionaryFromS", "Dictionary", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="Language")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Language : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Language object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Language CreateLanguage(global::System.Int32 id, global::System.String name)
        {
            Language language = new Language();
            language.Id = id;
            language.Name = name;
            return language;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "LanguageToL", "ToL")]
        public EntityCollection<ToL> ToLs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ToL>("Model3.LanguageToL", "ToL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ToL>("Model3.LanguageToL", "ToL", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "LanguageFromL", "FromL")]
        public EntityCollection<FromL> FromLs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FromL>("Model3.LanguageFromL", "FromL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FromL>("Model3.LanguageFromL", "FromL", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Location : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Location object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="pIN">Initial value of the PIN property.</param>
        /// <param name="street">Initial value of the street property.</param>
        /// <param name="publisherId">Initial value of the PublisherId property.</param>
        public static Location CreateLocation(global::System.Int32 id, global::System.String city, global::System.String state, global::System.String pIN, global::System.String street, global::System.Int32 publisherId)
        {
            Location location = new Location();
            location.Id = id;
            location.City = city;
            location.State = state;
            location.PIN = pIN;
            location.street = street;
            location.PublisherId = publisherId;
            return location;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PIN
        {
            get
            {
                return _PIN;
            }
            set
            {
                OnPINChanging(value);
                ReportPropertyChanging("PIN");
                _PIN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PIN");
                OnPINChanged();
            }
        }
        private global::System.String _PIN;
        partial void OnPINChanging(global::System.String value);
        partial void OnPINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String street
        {
            get
            {
                return _street;
            }
            set
            {
                OnstreetChanging(value);
                ReportPropertyChanging("street");
                _street = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("street");
                OnstreetChanged();
            }
        }
        private global::System.String _street;
        partial void OnstreetChanging(global::System.String value);
        partial void OnstreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PublisherId
        {
            get
            {
                return _PublisherId;
            }
            set
            {
                OnPublisherIdChanging(value);
                ReportPropertyChanging("PublisherId");
                _PublisherId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublisherId");
                OnPublisherIdChanged();
            }
        }
        private global::System.Int32 _PublisherId;
        partial void OnPublisherIdChanging(global::System.Int32 value);
        partial void OnPublisherIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "PublisherLocation", "Publisher")]
        public Publisher Publisher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("Model3.PublisherLocation", "Publisher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("Model3.PublisherLocation", "Publisher").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Publisher> PublisherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("Model3.PublisherLocation", "Publisher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Publisher>("Model3.PublisherLocation", "Publisher", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="Mention")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mention : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Mention object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static Mention CreateMention(global::System.Int32 id, global::System.String name, global::System.String type)
        {
            Mention mention = new Mention();
            mention.Id = id;
            mention.Name = name;
            mention.Type = type;
            return mention;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryMention", "Dictionary")]
        public EntityCollection<Dictionary> Dictionaries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Dictionary>("Model3.DictionaryMention", "Dictionary");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Dictionary>("Model3.DictionaryMention", "Dictionary", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="Publisher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Publisher : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Publisher object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static Publisher CreatePublisher(global::System.Int32 id, global::System.String name, global::System.Int32 address)
        {
            Publisher publisher = new Publisher();
            publisher.Id = id;
            publisher.Name = name;
            publisher.Address = address;
            return publisher;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.Int32 _Address;
        partial void OnAddressChanging(global::System.Int32 value);
        partial void OnAddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "BookPublisher", "Book")]
        public EntityCollection<Dictionary> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Dictionary>("Model3.BookPublisher", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Dictionary>("Model3.BookPublisher", "Book", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "PublisherLocation", "Location")]
        public EntityCollection<Location> Locations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Location>("Model3.PublisherLocation", "Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Location>("Model3.PublisherLocation", "Location", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="Script")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Script : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Script object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Script CreateScript(global::System.Int32 id)
        {
            Script script = new Script();
            script.Id = id;
            return script;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "ScriptFromS", "FromS")]
        public EntityCollection<FromS> FromS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FromS>("Model3.ScriptFromS", "FromS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FromS>("Model3.ScriptFromS", "FromS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "ScriptToS", "ToS")]
        public EntityCollection<ToS> ToS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ToS>("Model3.ScriptToS", "ToS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ToS>("Model3.ScriptToS", "ToS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="ToL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ToL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ToL object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="languageId">Initial value of the LanguageId property.</param>
        /// <param name="dictionaryId">Initial value of the DictionaryId property.</param>
        public static ToL CreateToL(global::System.Int32 id, global::System.Int32 languageId, global::System.Int32 dictionaryId)
        {
            ToL toL = new ToL();
            toL.Id = id;
            toL.LanguageId = languageId;
            toL.DictionaryId = dictionaryId;
            return toL;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                OnLanguageIdChanging(value);
                ReportPropertyChanging("LanguageId");
                _LanguageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LanguageId");
                OnLanguageIdChanged();
            }
        }
        private global::System.Int32 _LanguageId;
        partial void OnLanguageIdChanging(global::System.Int32 value);
        partial void OnLanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DictionaryId
        {
            get
            {
                return _DictionaryId;
            }
            set
            {
                OnDictionaryIdChanging(value);
                ReportPropertyChanging("DictionaryId");
                _DictionaryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DictionaryId");
                OnDictionaryIdChanged();
            }
        }
        private global::System.Int32 _DictionaryId;
        partial void OnDictionaryIdChanging(global::System.Int32 value);
        partial void OnDictionaryIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "LanguageToL", "Language")]
        public Language Language
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("Model3.LanguageToL", "Language").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("Model3.LanguageToL", "Language").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Language> LanguageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("Model3.LanguageToL", "Language");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Language>("Model3.LanguageToL", "Language", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryToL", "Dictionary")]
        public Dictionary Dictionary
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryToL", "Dictionary").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryToL", "Dictionary").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dictionary> DictionaryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryToL", "Dictionary");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dictionary>("Model3.DictionaryToL", "Dictionary", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model3", Name="ToS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ToS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ToS object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dictionaryId">Initial value of the DictionaryId property.</param>
        /// <param name="scriptId">Initial value of the ScriptId property.</param>
        public static ToS CreateToS(global::System.Int32 id, global::System.Int32 dictionaryId, global::System.Int32 scriptId)
        {
            ToS toS = new ToS();
            toS.Id = id;
            toS.DictionaryId = dictionaryId;
            toS.ScriptId = scriptId;
            return toS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DictionaryId
        {
            get
            {
                return _DictionaryId;
            }
            set
            {
                OnDictionaryIdChanging(value);
                ReportPropertyChanging("DictionaryId");
                _DictionaryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DictionaryId");
                OnDictionaryIdChanged();
            }
        }
        private global::System.Int32 _DictionaryId;
        partial void OnDictionaryIdChanging(global::System.Int32 value);
        partial void OnDictionaryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScriptId
        {
            get
            {
                return _ScriptId;
            }
            set
            {
                OnScriptIdChanging(value);
                ReportPropertyChanging("ScriptId");
                _ScriptId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScriptId");
                OnScriptIdChanged();
            }
        }
        private global::System.Int32 _ScriptId;
        partial void OnScriptIdChanging(global::System.Int32 value);
        partial void OnScriptIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "DictionaryToS", "Dictionary")]
        public Dictionary Dictionary
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryToS", "Dictionary").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryToS", "Dictionary").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dictionary> DictionaryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dictionary>("Model3.DictionaryToS", "Dictionary");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dictionary>("Model3.DictionaryToS", "Dictionary", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model3", "ScriptToS", "Script")]
        public Script Script
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Script>("Model3.ScriptToS", "Script").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Script>("Model3.ScriptToS", "Script").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Script> ScriptReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Script>("Model3.ScriptToS", "Script");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Script>("Model3.ScriptToS", "Script", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
